import React, { useState } from 'react'
import { useAuth } from '../context/AuthContext.jsx'
import TimetableGrid from '../components/TimetableGrid.jsx'
import StatusBadge from '../components/StatusBadge.jsx'
import { DEPARTMENTS, SAMPLE_TIMETABLE, TIMETABLE_STATUS } from '../data/dummyData.js'

export default function Timetable() {
  const { role } = useAuth()
  const [dept, setDept] = useState(role === 'admin' ? 'CSE' : role === 'hod' ? 'IT' : 'CSE')
  const [section, setSection] = useState('A')
  const [generating, setGenerating] = useState(false)

  const deptObj = DEPARTMENTS.find((d) => d.id === dept)
  const status = TIMETABLE_STATUS[dept]?.[section] || 'Draft'
  const hasData = dept === 'CSE' && section === 'A'

  const handleGenerate = () => {
    setGenerating(true)
    setTimeout(() => setGenerating(false), 1400)
  }

  return (
    <div>
      <div className="page-head">
        <div>
          <h1>{role === 'faculty' ? 'My Timetable' : 'Timetable'}</h1>
          <p className="sub">
            {role === 'faculty'
              ? 'Your weekly schedule across all assigned sections.'
              : 'Generated by the AI scheduling engine — constraint satisfaction with backtracking and heuristic optimization.'}
          </p>
        </div>
        {role !== 'faculty' && (
          <div className="toolbar">
            <select className="select-input" value={dept} onChange={(e) => { setDept(e.target.value); setSection(DEPARTMENTS.find(d => d.id === e.target.value).classes[0]) }}>
              {DEPARTMENTS.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}
            </select>
            <select className="select-input" value={section} onChange={(e) => setSection(e.target.value)}>
              {deptObj.classes.map((c) => <option key={c} value={c}>Section {c}</option>)}
            </select>
          </div>
        )}
      </div>

      <div className="panel">
        <div className="panel-head">
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <h3>{dept} — Section {section}</h3>
            <StatusBadge status={status} />
          </div>
          <RoleActions role={role} generating={generating} onGenerate={handleGenerate} />
        </div>

        {hasData ? (
          <TimetableGrid data={SAMPLE_TIMETABLE} />
        ) : (
          <div className="empty-note">
            No timetable generated yet for {dept} — Section {section} 
            
          </div>
        )}
      </div>
    </div>
  )
}

function RoleActions({ role, generating, onGenerate }) {
  if (role === 'faculty') return null
  return (
    <div className="toolbar">
      {(role === 'admin' || role === 'principal') && (
        <button className="btn btn-amber btn-sm" onClick={onGenerate} disabled={generating}>
          {generating ? 'Generating…' : 'Generate with AI'}
        </button>
      )}
      {(role === 'admin' || role === 'hod' || role === 'principal') && (
        <button className="btn btn-outline btn-sm">Run optimization</button>
      )}
      {role === 'admin' && <button className="btn btn-dark btn-sm">Submit to HOD</button>}
      {role === 'hod' && (
        <>
          <button className="btn btn-dark btn-sm">Approve</button>
          <button className="btn btn-danger-outline btn-sm">Reject</button>
        </>
      )}
      {role === 'principal' && <button className="btn btn-outline btn-sm">Override approval</button>}
      <button className="btn btn-outline btn-sm">Export ▾</button>
    </div>
  )
}
